#!/bin/bash

if [ $1 == "configure" ]; then
    if status xbian-xbmc-bridge | grep -q "running"; then
        # if config changed and xbian-xbmc-bridge was running, restart will not reread new configuration. according do doc, stop and start is needed
        stop -q xbian-xbmc-bridge 2>/dev/null
        start -q xbian-xbmc-bridge 2>/dev/null
    else
        status xbmc | grep -vq "running" || start -q xbian-xbmc-bridge 2>/dev/null
    fi
fi

exit 0
